# Generated by Django 3.1.3 on 2020-11-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Phone', models.IntegerField(default=35354365)),
                ('Email', models.EmailField(max_length=254)),
                ('Image', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
